// Writing knowledge for Manch: who the buyers are and how they talk, how to write in the
// Indian enterprise market, third-party facts the writer may use, objection answers, and
// a starter library of example messages. Researched from public sources on 2026-10-09
// (ids in src/lib/knowledge/sources.ts); findings are paraphrased, not copied.
//
// This is a starting point written without Manch's own sales history. Replace examples
// with real ones that got replies as soon as you have them — they beat anything here.
// Editable in Settings → Seller profile → Edit (full pack, "writing").
//
// Examples use <angle-bracket> placeholders. The writer imitates their shape and tone,
// never their details: every claim about a prospect must still come from researched facts.

import type { WritingKnowledge } from "./types";

export const MANCH_WRITING: WritingKnowledge = {
  market: {
    label: "Indian enterprise (B2B)",
    norms: [
      { text: "Start more formal than you think. For CXOs at traditional, family-run or public-sector companies, prefer 'Dear Mr./Ms. <Surname>'; 'Hi <first name>' suits digital-native companies and managers.", sources: ["tmf_india_culture"] },
      { text: "Decisions sit with senior leadership. Write to one or two people per company, not the whole buying group at once; reach the champion and the decision maker with different angles.", sources: ["tmf_india_culture", "hunter_2026"] },
      { text: "A soft 'we'll see' or 'it may be difficult' usually means no. Ask what the constraint is (time, budget, scope, risk) and offer a smaller, phased pilot.", sources: ["tmf_india_culture"] },
      { text: "Send Tuesday to Thursday. In APAC, afternoon sends outperformed mornings; avoid weekends.", sources: ["saleshandy_2026", "woodpecker_2026"] },
      { text: "Use Indian terms and units naturally — GSTIN, PAN, crore, ₹ — and name Indian regulations only when a fact or approved market fact supports it.", sources: [] },
      { text: "Never cold-message on WhatsApp. Confirm anything agreed in writing by email.", sources: ["tmf_india_culture"] },
    ],
  },

  personas: [
    {
      key: "cio_cdo",
      name: "CIO / CDO / Head of IT or Digital",
      role: "decision_maker",
      functions: ["data", "it"],
      titleHints: ["cio", "chief information", "cdo", "chief data", "chief digital", "cto", "head of it", "it head", "vp it", "head of digital", "digital transformation"],
      cares: [
        "Getting data foundations ready for AI — most Indian tech leaders say theirs aren't",
        "Proving ROI after a run of AI pilots that went nowhere",
        "Modernising the core (SAP S/4HANA, cloud) without creating tomorrow's legacy",
        "Being seen by the business as strategic, not just a service desk",
        "Security and the coming DPDP obligations",
      ],
      language: ["data foundation", "single source of truth", "golden record", "S/4 cut-over", "integration", "governance", "AI-ready data", "PoC"],
      avoid: ["'AI magic' or hype", "ROI promises", "anything that sounds like replacing SAP", "long feature lists"],
      opener: "Their modernisation or AI programme, then the master-data risk inside it.",
      sources: ["bain_india_2026", "dpdp_rules_2025"],
    },
    {
      key: "master_data_lead",
      name: "Head of Master Data / Data Governance / SAP CoE",
      role: "champion",
      functions: ["data", "it"],
      titleHints: ["master data", "mdm", "data governance", "head of data", "sap coe", "sap lead", "erp lead", "data quality", "enterprise architect"],
      cares: [
        "Duplicate and incomplete vendor and customer records",
        "A growing backlog of create/change requests and slow approvals",
        "Cleansing before an S/4HANA migration",
        "Data-quality KPIs that leadership actually looks at",
      ],
      language: ["duplicate vendors", "MDG", "data stewards", "maker-checker", "first-time-right", "cleansing", "change requests", "workflow"],
      avoid: ["vague 'data quality' talk — be concrete about the record and the field", "implying their team is failing"],
      opener: "A concrete record problem (duplicates, GSTIN–PAN mismatch, unverified bank details) tied to their programme or hiring.",
      sources: ["bain_india_2026", "authbridge_fmcg"],
    },
    {
      key: "cpo_procurement",
      name: "CPO / Head of Procurement",
      role: "decision_maker",
      functions: ["procurement"],
      titleHints: ["cpo", "chief procurement", "head of procurement", "vp procurement", "director procurement", "head of sourcing", "purchase head"],
      cares: [
        "Supplier risk and supply-chain visibility",
        "Onboarding new suppliers fast when plants or categories expand",
        "Breaking down silos between procurement, finance and plants",
        "Payment fraud through changed supplier bank details",
        "Audit findings and regulatory pressure",
      ],
      language: ["supplier onboarding cycle time", "vendor risk", "P2P", "supplier master", "bank account validation", "audit findings", "alternate sources"],
      avoid: ["generic cost-cutting claims", "promising savings figures"],
      opener: "An expansion, new plant or new category that means many new suppliers — then the risk and speed trade-off.",
      sources: ["deloitte_cpo_2025", "afp_fraud_2025"],
    },
    {
      key: "procurement_ops",
      name: "Vendor management / P2P / Accounts payable / Shared services",
      role: "champion",
      functions: ["procurement", "finance", "operations"],
      titleHints: ["vendor management", "supplier onboarding", "p2p", "procure to pay", "accounts payable", "shared services", "gbs", "procurement operations", "vendor master"],
      cares: [
        "Manual PAN, GSTIN and bank checks for every new vendor",
        "Failed payments and rework from wrong bank details",
        "E-invoices that can't be reported late any more (30-day IRP limit for larger taxpayers)",
        "Volumes rising without headcount",
      ],
      language: ["vendor creation request", "GSTIN validation", "penny drop", "bank account change request", "e-invoice", "IRP", "TAT"],
      avoid: ["executive-level strategy talk", "anything that sounds like more work for them"],
      opener: "A specific manual step they do every day, and how it scales badly with growth.",
      sources: ["gstn_einvoice_30d", "authbridge_fmcg"],
    },
    {
      key: "cfo_finance",
      name: "CFO / Finance Controller",
      role: "decision_maker",
      functions: ["finance"],
      titleHints: ["cfo", "chief financial", "finance director", "financial controller", "controller", "vp finance", "head of finance"],
      cares: [
        "Growth first — most Indian CFOs prioritise revenue over cost-cutting",
        "Controls, audit readiness and payment fraud",
        "Integrating acquisitions cleanly",
        "Automation that reduces finance workload",
      ],
      language: ["controls", "audit trail", "payment fraud", "compliance", "integration", "working capital"],
      avoid: ["ROI percentages", "technical detail", "more than one idea"],
      opener: "A deal, expansion or regulatory change and the control it puts at risk.",
      sources: ["deloitte_cfo_india_2025", "afp_fraud_2025", "gong_stats"],
    },
    {
      key: "sales_distribution",
      name: "Head of Distribution / Sales Operations / Channel",
      role: "decision_maker",
      functions: ["sales"],
      titleHints: ["head of distribution", "sales operations", "sales ops", "chief sales", "head of channel", "trade marketing", "distributor", "channel sales", "rural"],
      cares: [
        "Time from signing a distributor or retailer to their first order",
        "Expanding into new regions and rural markets",
        "Accurate partner data for schemes, credit and billing",
        "Manual KYC and approvals slowing the field team down",
      ],
      language: ["distributor onboarding TAT", "first order", "go-live", "beat expansion", "DMS", "retailer KYC", "credit limit"],
      avoid: ["IT jargon", "master-data vocabulary"],
      opener: "Their network expansion and how long it takes a new partner to start billing.",
      sources: ["parle_sap_2025", "authbridge_fmcg"],
    },
    {
      key: "compliance_risk",
      name: "Compliance / Risk / KYC / Audit / CISO",
      role: "influencer",
      functions: ["compliance", "security", "legal"],
      titleHints: ["compliance", "risk", "kyc", "audit", "ciso", "legal", "company secretary"],
      cares: ["KYC and consent done right at onboarding", "Audit trail for every record and change", "Preparing for DPDP obligations from May 2027", "Breach reporting and data retention"],
      language: ["audit trail", "consent", "KYC", "DPDP", "data principal", "retention", "maker-checker"],
      avoid: ["claiming Manch makes them 'compliant'", "legal advice", "certifications not in the seller pack"],
      opener: "A regulatory change and the onboarding step it touches.",
      sources: ["dpdp_rules_2025", "authbridge_fmcg"],
    },
  ],

  marketFacts: [
    { id: "bain_data_foundations", text: "About nine in ten Indian technology leaders say their data foundations aren't ready to scale.", attribution: "Bain & Company, India Enterprise Technology Report 2026", source: "bain_india_2026" },
    { id: "afp_vendor_impersonation", text: "Vendor impersonation was reported by 45% of organisations in a 2025 payments-fraud survey, up 11 points in a year.", attribution: "AFP Payments Fraud and Control Survey 2025", source: "afp_fraud_2025" },
    { id: "gst_einvoice_30_days", text: "Since April 2025, businesses with turnover of ₹10 crore or more can't report an e-invoice more than 30 days after its date.", attribution: "GSTN advisory", source: "gstn_einvoice_30d" },
    { id: "dpdp_2027", text: "Most DPDP Rules obligations — notice and consent, security safeguards, rights requests — apply from 13 May 2027.", attribution: "DPDP Rules 2025", source: "dpdp_rules_2025" },
    { id: "deloitte_cpo_silos", text: "Procurement leaders name siloed ways of working as their biggest barrier to delivering value (57%).", attribution: "Deloitte Global CPO Survey 2025", source: "deloitte_cpo_2025" },
  ],

  objections: [
    { key: "already_have_mdm", objection: "We already have SAP MDG / Informatica.", answer: "Keep it. Manch sits in front of it: it captures and validates external-party data (PAN, GSTIN, bank, KYC) at the point of entry and hands clean records to the MDM and ERP you already run. Ask where bad records come in today.", sources: [] },
    { key: "build_in_house", objection: "Our IT team can build this on Power Apps / Appian.", answer: "They can build the forms; the verification APIs, onboarding flows and audit trail are what take time. Offer to compare build effort against a 4–8 week go-live on pre-built workflows.", sources: [] },
    { key: "mid_migration", objection: "We're in the middle of S/4HANA — no bandwidth.", answer: "That is when it pays most: clean vendor and customer masters before cut-over. Suggest a small, phased start on one entity (e.g. new vendors only) that doesn't touch the migration team.", sources: ["tmf_india_culture"] },
    { key: "not_priority", objection: "Not a priority right now.", answer: "Ask what would make it one (an audit, an expansion, a migration date) and offer a one-page summary to keep on file; check back after that event.", sources: ["tmf_india_culture"] },
    { key: "send_info", objection: "Send me some information.", answer: "Send one page tied to their trigger, not a brochure, and ask one question that tells you who owns the problem.", sources: ["gartner_buyers_2025"] },
    { key: "security_dpdp", objection: "How do you handle security and data protection?", answer: "Hand this to the Manch team with the security pack. Never state certifications, hosting or compliance status that isn't in the seller pack.", sources: ["dpdp_rules_2025"] },
    { key: "budget_frozen", objection: "Budgets are frozen this year.", answer: "Ask when planning for next year starts and offer a scoped pilot with a clear success measure that can be funded from an existing programme.", sources: ["tmf_india_culture"] },
  ],

  examples: [
    {
      id: "ex_cio_first_s4",
      play: "email_first",
      persona: "cio_cdo",
      useCase: "customer_master",
      trigger: "erp_migration",
      quality: "good",
      subject: "<Company>'s S/4HANA cut-over and master data",
      body: "Hi <first name>,\n\nSaw that <Company> has started its move to SAP S/4HANA, with go-live planned for <date from the facts>.\n\nIn programmes like this, vendor and customer masters are often what slows cut-over: duplicates, and GST and bank details nobody wants to migrate as they are. Is that on your list?\n\nManch checks those details at the point of entry and passes clean records to SAP, so data stays clean after go-live too.\n\nWorth comparing notes on how other teams phased it?",
      why: "Opens on their own programme with two concrete details, names the likely pain as a question, one capability, one soft interest ask.",
    },
    {
      id: "ex_mdm_first_duplicates",
      play: "email_first",
      persona: "master_data_lead",
      useCase: "vendor_onboarding",
      trigger: "mdm_replacement",
      quality: "good",
      subject: "Vendor cleansing at <Company>",
      body: "Hi <first name>,\n\n<Company>'s careers page lists a master data analyst role focused on vendor cleansing, which usually means the backlog is growing.\n\nIn most master data teams, more time goes into fixing records than approving them: the same supplier created twice, a GSTIN that doesn't match the PAN, bank details nobody verified.\n\nManch validates PAN, GSTIN and bank details while the vendor fills in the form, so stewards approve instead of correct.\n\nWould a short look at that flow be useful?",
      why: "Uses a hiring signal as the trigger and speaks the steward's language (records, fields), without implying the team is failing.",
    },
    {
      id: "ex_cpo_first_plant",
      play: "email_first",
      persona: "cpo_procurement",
      useCase: "vendor_onboarding",
      trigger: "channel_expansion",
      quality: "good",
      subject: "Supplier onboarding for the <place> plant",
      body: "Hi <first name>,\n\nCongratulations on the new <place> plant announced last month. That usually brings a wave of new local suppliers to onboard.\n\nWhen volume jumps, checks tend to slip: bank details changed by email, GST registrations not re-verified. Vendor impersonation is now one of the most common payment-fraud routes finance teams report.\n\nManch runs those checks automatically at onboarding and on every change request, with a full audit trail.\n\nIs onboarding speed or supplier risk the bigger concern for you right now?",
      why: "Links an expansion to a risk the CPO owns, uses an approved market fact without a number, and asks a choice question that is easy to answer.",
    },
    {
      id: "ex_sales_first_distributors",
      play: "email_first",
      persona: "sales_distribution",
      useCase: "distributor_onboarding",
      trigger: "channel_expansion",
      quality: "good",
      subject: "<Company>'s distributor expansion in <region>",
      body: "Hi <first name>,\n\nRead that <Company> plans to add <number> distributors in <region> this year.\n\nAt that pace the bottleneck is often the paperwork, not the pipeline: KYC, GST and bank checks done by hand before a distributor can place a first order.\n\nManch digitises that onboarding end to end, and has cut partner onboarding from 7 days to 7 hours for one customer.\n\nIs time to first order something your team tracks?",
      why: "Speaks the sales leader's metric (time to first order), not IT vocabulary; one approved proof point.",
    },
    {
      id: "ex_cfo_first_merger",
      play: "email_first",
      persona: "cfo_finance",
      useCase: "vendor_onboarding",
      trigger: "ma_integration",
      quality: "good",
      subject: "Vendor masters after the <target> deal",
      body: "Dear Mr./Ms. <Surname>,\n\nWith <Company>'s acquisition of <target> closing, two vendor masters will need to become one.\n\nMergers are where payment controls get tested: duplicate suppliers, and bank details that were never verified in one of the systems.\n\nManch verifies PAN, GSTIN and bank accounts for every vendor record and change, and keeps the audit trail auditors ask for.\n\nIs the vendor master part of your integration plan?",
      why: "Formal greeting for a CFO at a traditional company, one control at risk, no ROI language.",
    },
    {
      id: "ex_cio_follow_bain",
      play: "email_follow_up",
      persona: "cio_cdo",
      useCase: "customer_master",
      trigger: "erp_migration",
      quality: "good",
      subject: "Re: <Company>'s S/4HANA cut-over and master data",
      body: "Hi <first name>,\n\nAdding one thing to my note on the S/4HANA programme.\n\nBain found this year that about nine in ten Indian technology leaders feel their data foundations aren't ready to scale.\n\nA large beverage bottler fixed this at entry with Manch, replacing several legacy MDM tools and validating every new customer before it reached the ERP.\n\nWould a short summary of how they phased it help?",
      why: "A genuinely new reason (third-party fact + customer story), shorter than the first email, same soft ask in new words.",
    },
    {
      id: "ex_ap_follow_einvoice",
      play: "email_follow_up",
      persona: "procurement_ops",
      useCase: "vendor_onboarding",
      trigger: "compliance_mandate",
      quality: "good",
      subject: "Re: Vendor onboarding at <Company>",
      body: "Hi <first name>,\n\nOne more thought, specific to accounts payable.\n\nSince April 2025, larger businesses can't report an e-invoice more than 30 days late, so a supplier created with a wrong GSTIN now costs more than a correction.\n\nManch checks the GSTIN against the PAN when the vendor is created, before the first invoice arrives.\n\nIs GSTIN mismatch something your team sees often?",
      why: "Ties a real regulatory change to a daily AP task; practical, not strategic.",
    },
    {
      id: "ex_cpo_last",
      play: "email_last",
      persona: "cpo_procurement",
      useCase: "vendor_onboarding",
      quality: "good",
      subject: "Re: Supplier onboarding for the <place> plant",
      body: "Hi <first name>,\n\nI'll leave it here after this note.\n\nIf supplier onboarding and bank-detail checks become a priority as the new plant ramps up, I'm happy to send a one-page summary instead of a call.\n\nIs someone else on your team closer to this, or should I check back next quarter?",
      why: "Makes 'not now' or a referral easy, no guilt, no new claims.",
    },
    {
      id: "ex_mdm_connect",
      play: "linkedin_connect",
      persona: "master_data_lead",
      quality: "good",
      body: "Hi <first name>, saw <Company> is hiring for vendor data cleansing ahead of S/4HANA. I work on master data onboarding in India and would be glad to connect.",
      why: "One specific reason, no pitch, under 200 characters.",
    },
    {
      id: "ex_sales_connect",
      play: "linkedin_connect",
      persona: "sales_distribution",
      quality: "good",
      body: "Hi <first name>, congratulations on <Company>'s expansion into <region>. I follow distributor onboarding closely and would be glad to connect.",
      why: "Congratulates on something real; no product, no ask for time.",
    },
    {
      id: "ex_cio_li_first",
      play: "linkedin_first_message",
      persona: "cio_cdo",
      quality: "good",
      body: "Thanks for connecting, <first name>. Curious how <Company> is approaching vendor and customer master data in the S/4HANA move: cleanse before cut-over, or fix after go-live?",
      why: "Chat-length, one easy question about their world, no pitch.",
    },
    {
      id: "ex_ap_li_first",
      play: "linkedin_first_message",
      persona: "procurement_ops",
      quality: "good",
      body: "Thanks for connecting, <first name>. With new suppliers coming in for the <place> plant, are GST and bank checks still done by your team by hand, or already automated?",
      why: "Practical question the person can answer in one line.",
    },
    {
      id: "ex_sales_li_follow",
      play: "linkedin_follow_up",
      persona: "sales_distribution",
      quality: "good",
      body: "One data point that might help: a food-delivery network automated partner registration and verification with Manch and removed its manual compliance checks. Is onboarding speed a focus for you this year?",
      why: "Gives something useful (an approved customer story) and one easy question.",
    },
    {
      id: "bad_generic_pitch",
      play: "email_first",
      persona: "cio_cdo",
      quality: "bad",
      subject: "Revolutionise your data with Manch Agentic AI platform today",
      body: "Hi <first name>,\n\nI hope this email finds you well. I came across your company and wanted to reach out because Manch is a revolutionary agentic AI platform that can streamline your operations and unlock the full potential of your data. We work with Fortune 500 companies and guarantee 10x ROI.\n\nCan we schedule a 30-minute call on Tuesday at 3 pm? Would you also like a demo? I've attached three case studies.",
      why: "Nothing about them, all about the seller; hype, an ROI guarantee, a long subject, a fixed meeting time, two asks and attachments.",
    },
    {
      id: "bad_bump",
      play: "email_follow_up",
      persona: "procurement_ops",
      quality: "bad",
      subject: "Re: Following up",
      body: "Hi <first name>,\n\nJust checking in on my last email. Did you get a chance to read it? Bumping this to the top of your inbox in case it got buried.",
      why: "No new reason to reply, guilt, filler phrases.",
    },
    {
      id: "bad_pitch_connect",
      play: "linkedin_connect",
      persona: "sales_distribution",
      quality: "bad",
      body: "Hi <first name>, Manch helps enterprises like yours cut onboarding time 10x with agentic AI MDM. Can we set up a quick call this week to show you a demo? https://manchtech.com",
      why: "A pitch, a link and a meeting request in a connection note; an unsupported '10x'.",
    },
  ],
};
